
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - mern-network

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - mern-network
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
